/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include "GestorBiblioteca.h"
#include <stdio.h>
#include <stdlib.h>
#include <rpc/pmap_clnt.h>
#include <string.h>
#include <memory.h>
#include <sys/socket.h>
#include <netinet/in.h>

#ifndef SIG_PF
#define SIG_PF void(*)(int)
#endif

static void
gestorbiblioteca_1(struct svc_req *rqstp, register SVCXPRT *transp)
{
	union {
		Cadena conexion_1_arg;
		int desconexion_1_arg;
		TFichero cargardatos_1_arg;
		int guardardatos_1_arg;
		TNuevo nuevolibro_1_arg;
		TComRet comprar_1_arg;
		TComRet retirar_1_arg;
		TOrdenacion ordenar_1_arg;
		int nlibros_1_arg;
		TConsulta buscar_1_arg;
		TPosicion descargar_1_arg;
		TPosicion prestar_1_arg;
		TPosicion devolver_1_arg;
	} argument;
	char *result;
	xdrproc_t _xdr_argument, _xdr_result;
	char *(*local)(char *, struct svc_req *);

	switch (rqstp->rq_proc) {
	case NULLPROC:
		(void) svc_sendreply (transp, (xdrproc_t) xdr_void, (char *)NULL);
		return;

	case Conexion:
		_xdr_argument = (xdrproc_t) xdr_Cadena;
		_xdr_result = (xdrproc_t) xdr_int;
		local = (char *(*)(char *, struct svc_req *)) conexion_1_svc;
		break;

	case Desconexion:
		_xdr_argument = (xdrproc_t) xdr_int;
		_xdr_result = (xdrproc_t) xdr_bool;
		local = (char *(*)(char *, struct svc_req *)) desconexion_1_svc;
		break;

	case CargarDatos:
		_xdr_argument = (xdrproc_t) xdr_TFichero;
		_xdr_result = (xdrproc_t) xdr_int;
		local = (char *(*)(char *, struct svc_req *)) cargardatos_1_svc;
		break;

	case GuardarDatos:
		_xdr_argument = (xdrproc_t) xdr_int;
		_xdr_result = (xdrproc_t) xdr_bool;
		local = (char *(*)(char *, struct svc_req *)) guardardatos_1_svc;
		break;

	case NuevoLibro:
		_xdr_argument = (xdrproc_t) xdr_TNuevo;
		_xdr_result = (xdrproc_t) xdr_int;
		local = (char *(*)(char *, struct svc_req *)) nuevolibro_1_svc;
		break;

	case Comprar:
		_xdr_argument = (xdrproc_t) xdr_TComRet;
		_xdr_result = (xdrproc_t) xdr_int;
		local = (char *(*)(char *, struct svc_req *)) comprar_1_svc;
		break;

	case Retirar:
		_xdr_argument = (xdrproc_t) xdr_TComRet;
		_xdr_result = (xdrproc_t) xdr_int;
		local = (char *(*)(char *, struct svc_req *)) retirar_1_svc;
		break;

	case Ordenar:
		_xdr_argument = (xdrproc_t) xdr_TOrdenacion;
		_xdr_result = (xdrproc_t) xdr_bool;
		local = (char *(*)(char *, struct svc_req *)) ordenar_1_svc;
		break;

	case NLibros:
		_xdr_argument = (xdrproc_t) xdr_int;
		_xdr_result = (xdrproc_t) xdr_int;
		local = (char *(*)(char *, struct svc_req *)) nlibros_1_svc;
		break;

	case Buscar:
		_xdr_argument = (xdrproc_t) xdr_TConsulta;
		_xdr_result = (xdrproc_t) xdr_int;
		local = (char *(*)(char *, struct svc_req *)) buscar_1_svc;
		break;

	case Descargar:
		_xdr_argument = (xdrproc_t) xdr_TPosicion;
		_xdr_result = (xdrproc_t) xdr_TLibro;
		local = (char *(*)(char *, struct svc_req *)) descargar_1_svc;
		break;

	case Prestar:
		_xdr_argument = (xdrproc_t) xdr_TPosicion;
		_xdr_result = (xdrproc_t) xdr_int;
		local = (char *(*)(char *, struct svc_req *)) prestar_1_svc;
		break;

	case Devolver:
		_xdr_argument = (xdrproc_t) xdr_TPosicion;
		_xdr_result = (xdrproc_t) xdr_int;
		local = (char *(*)(char *, struct svc_req *)) devolver_1_svc;
		break;

	default:
		svcerr_noproc (transp);
		return;
	}
	memset ((char *)&argument, 0, sizeof (argument));
	if (!svc_getargs (transp, (xdrproc_t) _xdr_argument, (caddr_t) &argument)) {
		svcerr_decode (transp);
		return;
	}
	result = (*local)((char *)&argument, rqstp);
	if (result != NULL && !svc_sendreply(transp, (xdrproc_t) _xdr_result, result)) {
		svcerr_systemerr (transp);
	}
	if (!svc_freeargs (transp, (xdrproc_t) _xdr_argument, (caddr_t) &argument)) {
		fprintf (stderr, "%s", "unable to free arguments");
		exit (1);
	}
	return;
}

int
main (int argc, char **argv)
{
	register SVCXPRT *transp;

	pmap_unset (GESTORBIBLIOTECA, GESTORBIBLIOTECA_VER);

	transp = svcudp_create(RPC_ANYSOCK);
	if (transp == NULL) {
		fprintf (stderr, "%s", "cannot create udp service.");
		exit(1);
	}
	if (!svc_register(transp, GESTORBIBLIOTECA, GESTORBIBLIOTECA_VER, gestorbiblioteca_1, IPPROTO_UDP)) {
		fprintf (stderr, "%s", "unable to register (GESTORBIBLIOTECA, GESTORBIBLIOTECA_VER, udp).");
		exit(1);
	}

	transp = svctcp_create(RPC_ANYSOCK, 0, 0);
	if (transp == NULL) {
		fprintf (stderr, "%s", "cannot create tcp service.");
		exit(1);
	}
	if (!svc_register(transp, GESTORBIBLIOTECA, GESTORBIBLIOTECA_VER, gestorbiblioteca_1, IPPROTO_TCP)) {
		fprintf (stderr, "%s", "unable to register (GESTORBIBLIOTECA, GESTORBIBLIOTECA_VER, tcp).");
		exit(1);
	}

	svc_run ();
	fprintf (stderr, "%s", "svc_run returned");
	exit (1);
	/* NOTREACHED */
}
